with-expecter: True
dir: "mocks/{{ .PackageName }}"
packages:
  github.com/lukasjarosch/skipper:
    interfaces:
      ValueReferenceSource:
  github.com/lukasjarosch/skipper/reference:
    interfaces:
      ValueSource:
      ValueTarget:
