with-expecter: True
dir: "mocks/"
packages:
  github.com/lukasjarosch/skipper:
    interfaces:
      ValueReferenceSource:
      ValueReferenceTarget:
      # Codec:
      # DataContainer:
      # ReferenceValueSource:
      # ReferenceSourceGetter:
      # ReferenceSourceRelativeGetter:
