with-expecter: True
dir: "mocks/{{ .PackageName }}"
packages:
  github.com/lukasjarosch/skipper:
    interfaces:
      ValueReferenceSource:
      PathValueSource:
      VariableSource:
  github.com/lukasjarosch/skipper/expression:
    interfaces:
      PathValueProvider:
  github.com/lukasjarosch/skipper/reference:
    interfaces:
      ValueSource:
      ValueTarget:
