with-expecter: True
dir: "mocks/"
packages:
  github.com/lukasjarosch/skipper:
    interfaces:
      Codec:
      DataContainer:
      ReferenceValueSource:
      ReferenceSourceGetter:
      ReferenceSourceRelativeGetter:
