---
common:
  version: ">= 0.14"
  backend:
    address: ${gitlab:common:base_url}
    password: ?{plain:targets/${target_name}/someSecret}
    multipleSecrets: ?{plain:targets/${target_name}/someSecret}---?{plain:targets/${target_name}/anotherSecret}
    nonExistingSecretWithAlternativeAction: ?{plain:targets/${target_name}/createdSecret||randomstring:64}
    newDriver: ?{base64:targets/${target_name}/newDriver||randomstring:32}
    state_name: ${target_name}.tfstate
