---
target:
  skipper:
    use: 
      - azure.*
    components:
      - output_path: .
        input_paths:
          - AzureReadme.md
          - inventory.json
        rename:
          - input_path: AzureReadme.md
            filename: README.md
    copy:
      - source: inventory.json
        target: something/foobar.json
    secrets:
      drivers:
        azurekv: 
          ignore_version: true
          key_id: "https://kv-dev-infra-platform.vault.azure.net/keys/dev-infra-secrets-key/6e0360a098eb4808af5ec1f970d399c0"

  secrets:
    test1: ?{azurekv:targets/${target_name}/test1||randomstring:32}
    test2: ?{azurekv:targets/${target_name}/test2||randomstring:64}
    test3: ?{azurekv:targets/${target_name}/test2}

  test: ${target_name}
  alphaNum: "%{loweralpha:${azure:common:foo:bar}}"

