---
target:
  skipper:
    use: 
      - azure.*
    components:
      - output_path: .
        input_paths:
          - AzureReadme.md
          - inventory.json
        rename:
          - input_path: AzureReadme.md
            filename: README.md
    copy:
      - source: inventory.json
        target: something/foobar.json
    secrets:
      drivers:
        azurekv: 
          ignore_version: true
          key_id: "https://kv-markhub-sandbox-lukas.vault.azure.net/keys/sandbox-lukas-secrets-key/e1dd7010c47247da8b57782cbb8c4668"

  secrets:
    rsa: ?{azurekv:targets/${target_name}/rsa}

  test: ${target_name}
  alphaNum: "%{loweralpha:${azure:common:foo:bar}}"

  import: ${azure:common:this}
