---
target:
  use: 
    - azure.common
    - azure.resources
    - gitlab.common
    - terraform.identifiers
    - terraform.common

  # WIP: idea for secret management (also add in the use key)
  skipper:
    use: 
      - azure.common
      - azure.resources
      - gitlab.common
      - terraform.identifiers
      - terraform.common
    secrets:
      drivers:
        azurekv:
          someKey: someValue 
      keys:
        aes: "some-hardcoded-aes-key" # introduce ?{env:ENV_VAR} as secret variable driver
        azurekv: "https://...."

  azure:
    common:
      subscription_id: "45e4fca6-f05b-4354-951a-3ea194d2da85" # random uuid

  # Refactoring terraform identifiers has never been easier. 
  # Just change one variable from the imported class and you're done :)
  terraform:
    identifiers:
      resource_group: "changed_identifier"
