// Code generated by mockery v2.34.2. DO NOT EDIT.

package skipper

import (
	data "github.com/lukasjarosch/skipper/data"
	mock "github.com/stretchr/testify/mock"
)

// MockReferenceSourceGetter is an autogenerated mock type for the ReferenceSourceGetter type
type MockReferenceSourceGetter struct {
	mock.Mock
}

type MockReferenceSourceGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReferenceSourceGetter) EXPECT() *MockReferenceSourceGetter_Expecter {
	return &MockReferenceSourceGetter_Expecter{mock: &_m.Mock}
}

// GetPath provides a mock function with given fields: path
func (_m *MockReferenceSourceGetter) GetPath(path data.Path) (data.Value, error) {
	ret := _m.Called(path)

	var r0 data.Value
	var r1 error
	if rf, ok := ret.Get(0).(func(data.Path) (data.Value, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(data.Path) data.Value); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(data.Value)
	}

	if rf, ok := ret.Get(1).(func(data.Path) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReferenceSourceGetter_GetPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPath'
type MockReferenceSourceGetter_GetPath_Call struct {
	*mock.Call
}

// GetPath is a helper method to define mock.On call
//   - path data.Path
func (_e *MockReferenceSourceGetter_Expecter) GetPath(path interface{}) *MockReferenceSourceGetter_GetPath_Call {
	return &MockReferenceSourceGetter_GetPath_Call{Call: _e.mock.On("GetPath", path)}
}

func (_c *MockReferenceSourceGetter_GetPath_Call) Run(run func(path data.Path)) *MockReferenceSourceGetter_GetPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(data.Path))
	})
	return _c
}

func (_c *MockReferenceSourceGetter_GetPath_Call) Return(_a0 data.Value, _a1 error) *MockReferenceSourceGetter_GetPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReferenceSourceGetter_GetPath_Call) RunAndReturn(run func(data.Path) (data.Value, error)) *MockReferenceSourceGetter_GetPath_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReferenceSourceGetter creates a new instance of MockReferenceSourceGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReferenceSourceGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReferenceSourceGetter {
	mock := &MockReferenceSourceGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
