// Code generated by mockery v2.34.2. DO NOT EDIT.

package skipper

import (
	data "github.com/lukasjarosch/skipper/data"
	mock "github.com/stretchr/testify/mock"
)

// MockValueReferenceSource is an autogenerated mock type for the ValueReferenceSource type
type MockValueReferenceSource struct {
	mock.Mock
}

type MockValueReferenceSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValueReferenceSource) EXPECT() *MockValueReferenceSource_Expecter {
	return &MockValueReferenceSource_Expecter{mock: &_m.Mock}
}

// AbsolutePath provides a mock function with given fields: path, context
func (_m *MockValueReferenceSource) AbsolutePath(path data.Path, context data.Path) (data.Path, error) {
	ret := _m.Called(path, context)

	var r0 data.Path
	var r1 error
	if rf, ok := ret.Get(0).(func(data.Path, data.Path) (data.Path, error)); ok {
		return rf(path, context)
	}
	if rf, ok := ret.Get(0).(func(data.Path, data.Path) data.Path); ok {
		r0 = rf(path, context)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(data.Path)
		}
	}

	if rf, ok := ret.Get(1).(func(data.Path, data.Path) error); ok {
		r1 = rf(path, context)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockValueReferenceSource_AbsolutePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbsolutePath'
type MockValueReferenceSource_AbsolutePath_Call struct {
	*mock.Call
}

// AbsolutePath is a helper method to define mock.On call
//   - path data.Path
//   - context data.Path
func (_e *MockValueReferenceSource_Expecter) AbsolutePath(path interface{}, context interface{}) *MockValueReferenceSource_AbsolutePath_Call {
	return &MockValueReferenceSource_AbsolutePath_Call{Call: _e.mock.On("AbsolutePath", path, context)}
}

func (_c *MockValueReferenceSource_AbsolutePath_Call) Run(run func(path data.Path, context data.Path)) *MockValueReferenceSource_AbsolutePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(data.Path), args[1].(data.Path))
	})
	return _c
}

func (_c *MockValueReferenceSource_AbsolutePath_Call) Return(_a0 data.Path, _a1 error) *MockValueReferenceSource_AbsolutePath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockValueReferenceSource_AbsolutePath_Call) RunAndReturn(run func(data.Path, data.Path) (data.Path, error)) *MockValueReferenceSource_AbsolutePath_Call {
	_c.Call.Return(run)
	return _c
}

// Values provides a mock function with given fields:
func (_m *MockValueReferenceSource) Values() map[string]data.Value {
	ret := _m.Called()

	var r0 map[string]data.Value
	if rf, ok := ret.Get(0).(func() map[string]data.Value); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]data.Value)
		}
	}

	return r0
}

// MockValueReferenceSource_Values_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Values'
type MockValueReferenceSource_Values_Call struct {
	*mock.Call
}

// Values is a helper method to define mock.On call
func (_e *MockValueReferenceSource_Expecter) Values() *MockValueReferenceSource_Values_Call {
	return &MockValueReferenceSource_Values_Call{Call: _e.mock.On("Values")}
}

func (_c *MockValueReferenceSource_Values_Call) Run(run func()) *MockValueReferenceSource_Values_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValueReferenceSource_Values_Call) Return(_a0 map[string]data.Value) *MockValueReferenceSource_Values_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValueReferenceSource_Values_Call) RunAndReturn(run func() map[string]data.Value) *MockValueReferenceSource_Values_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockValueReferenceSource creates a new instance of MockValueReferenceSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValueReferenceSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValueReferenceSource {
	mock := &MockValueReferenceSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
