// Code generated by mockery v2.34.2. DO NOT EDIT.

package skipper

import (
	data "github.com/lukasjarosch/skipper/data"
	mock "github.com/stretchr/testify/mock"
)

// MockDataContainer is an autogenerated mock type for the DataContainer type
type MockDataContainer struct {
	mock.Mock
}

type MockDataContainer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDataContainer) EXPECT() *MockDataContainer_Expecter {
	return &MockDataContainer_Expecter{mock: &_m.Mock}
}

// AbsolutePath provides a mock function with given fields: path, context
func (_m *MockDataContainer) AbsolutePath(path data.Path, context data.Path) (data.Path, error) {
	ret := _m.Called(path, context)

	var r0 data.Path
	var r1 error
	if rf, ok := ret.Get(0).(func(data.Path, data.Path) (data.Path, error)); ok {
		return rf(path, context)
	}
	if rf, ok := ret.Get(0).(func(data.Path, data.Path) data.Path); ok {
		r0 = rf(path, context)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(data.Path)
		}
	}

	if rf, ok := ret.Get(1).(func(data.Path, data.Path) error); ok {
		r1 = rf(path, context)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDataContainer_AbsolutePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbsolutePath'
type MockDataContainer_AbsolutePath_Call struct {
	*mock.Call
}

// AbsolutePath is a helper method to define mock.On call
//   - path data.Path
//   - context data.Path
func (_e *MockDataContainer_Expecter) AbsolutePath(path interface{}, context interface{}) *MockDataContainer_AbsolutePath_Call {
	return &MockDataContainer_AbsolutePath_Call{Call: _e.mock.On("AbsolutePath", path, context)}
}

func (_c *MockDataContainer_AbsolutePath_Call) Run(run func(path data.Path, context data.Path)) *MockDataContainer_AbsolutePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(data.Path), args[1].(data.Path))
	})
	return _c
}

func (_c *MockDataContainer_AbsolutePath_Call) Return(_a0 data.Path, _a1 error) *MockDataContainer_AbsolutePath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDataContainer_AbsolutePath_Call) RunAndReturn(run func(data.Path, data.Path) (data.Path, error)) *MockDataContainer_AbsolutePath_Call {
	_c.Call.Return(run)
	return _c
}

// AllPaths provides a mock function with given fields:
func (_m *MockDataContainer) AllPaths() []data.Path {
	ret := _m.Called()

	var r0 []data.Path
	if rf, ok := ret.Get(0).(func() []data.Path); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]data.Path)
		}
	}

	return r0
}

// MockDataContainer_AllPaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllPaths'
type MockDataContainer_AllPaths_Call struct {
	*mock.Call
}

// AllPaths is a helper method to define mock.On call
func (_e *MockDataContainer_Expecter) AllPaths() *MockDataContainer_AllPaths_Call {
	return &MockDataContainer_AllPaths_Call{Call: _e.mock.On("AllPaths")}
}

func (_c *MockDataContainer_AllPaths_Call) Run(run func()) *MockDataContainer_AllPaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDataContainer_AllPaths_Call) Return(_a0 []data.Path) *MockDataContainer_AllPaths_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDataContainer_AllPaths_Call) RunAndReturn(run func() []data.Path) *MockDataContainer_AllPaths_Call {
	_c.Call.Return(run)
	return _c
}

// GetPath provides a mock function with given fields: _a0
func (_m *MockDataContainer) GetPath(_a0 data.Path) (data.Value, error) {
	ret := _m.Called(_a0)

	var r0 data.Value
	var r1 error
	if rf, ok := ret.Get(0).(func(data.Path) (data.Value, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(data.Path) data.Value); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(data.Value)
	}

	if rf, ok := ret.Get(1).(func(data.Path) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDataContainer_GetPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPath'
type MockDataContainer_GetPath_Call struct {
	*mock.Call
}

// GetPath is a helper method to define mock.On call
//   - _a0 data.Path
func (_e *MockDataContainer_Expecter) GetPath(_a0 interface{}) *MockDataContainer_GetPath_Call {
	return &MockDataContainer_GetPath_Call{Call: _e.mock.On("GetPath", _a0)}
}

func (_c *MockDataContainer_GetPath_Call) Run(run func(_a0 data.Path)) *MockDataContainer_GetPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(data.Path))
	})
	return _c
}

func (_c *MockDataContainer_GetPath_Call) Return(_a0 data.Value, _a1 error) *MockDataContainer_GetPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDataContainer_GetPath_Call) RunAndReturn(run func(data.Path) (data.Value, error)) *MockDataContainer_GetPath_Call {
	_c.Call.Return(run)
	return _c
}

// LeafPaths provides a mock function with given fields:
func (_m *MockDataContainer) LeafPaths() []data.Path {
	ret := _m.Called()

	var r0 []data.Path
	if rf, ok := ret.Get(0).(func() []data.Path); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]data.Path)
		}
	}

	return r0
}

// MockDataContainer_LeafPaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeafPaths'
type MockDataContainer_LeafPaths_Call struct {
	*mock.Call
}

// LeafPaths is a helper method to define mock.On call
func (_e *MockDataContainer_Expecter) LeafPaths() *MockDataContainer_LeafPaths_Call {
	return &MockDataContainer_LeafPaths_Call{Call: _e.mock.On("LeafPaths")}
}

func (_c *MockDataContainer_LeafPaths_Call) Run(run func()) *MockDataContainer_LeafPaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDataContainer_LeafPaths_Call) Return(_a0 []data.Path) *MockDataContainer_LeafPaths_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDataContainer_LeafPaths_Call) RunAndReturn(run func() []data.Path) *MockDataContainer_LeafPaths_Call {
	_c.Call.Return(run)
	return _c
}

// SetPath provides a mock function with given fields: _a0, _a1
func (_m *MockDataContainer) SetPath(_a0 data.Path, _a1 interface{}) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(data.Path, interface{}) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDataContainer_SetPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPath'
type MockDataContainer_SetPath_Call struct {
	*mock.Call
}

// SetPath is a helper method to define mock.On call
//   - _a0 data.Path
//   - _a1 interface{}
func (_e *MockDataContainer_Expecter) SetPath(_a0 interface{}, _a1 interface{}) *MockDataContainer_SetPath_Call {
	return &MockDataContainer_SetPath_Call{Call: _e.mock.On("SetPath", _a0, _a1)}
}

func (_c *MockDataContainer_SetPath_Call) Run(run func(_a0 data.Path, _a1 interface{})) *MockDataContainer_SetPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(data.Path), args[1].(interface{}))
	})
	return _c
}

func (_c *MockDataContainer_SetPath_Call) Return(_a0 error) *MockDataContainer_SetPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDataContainer_SetPath_Call) RunAndReturn(run func(data.Path, interface{}) error) *MockDataContainer_SetPath_Call {
	_c.Call.Return(run)
	return _c
}

// Walk provides a mock function with given fields: _a0
func (_m *MockDataContainer) Walk(_a0 func(data.Path, data.Value, bool) error) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(func(data.Path, data.Value, bool) error) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDataContainer_Walk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Walk'
type MockDataContainer_Walk_Call struct {
	*mock.Call
}

// Walk is a helper method to define mock.On call
//   - _a0 func(data.Path , data.Value , bool) error
func (_e *MockDataContainer_Expecter) Walk(_a0 interface{}) *MockDataContainer_Walk_Call {
	return &MockDataContainer_Walk_Call{Call: _e.mock.On("Walk", _a0)}
}

func (_c *MockDataContainer_Walk_Call) Run(run func(_a0 func(data.Path, data.Value, bool) error)) *MockDataContainer_Walk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(data.Path, data.Value, bool) error))
	})
	return _c
}

func (_c *MockDataContainer_Walk_Call) Return(_a0 error) *MockDataContainer_Walk_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDataContainer_Walk_Call) RunAndReturn(run func(func(data.Path, data.Value, bool) error) error) *MockDataContainer_Walk_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDataContainer creates a new instance of MockDataContainer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDataContainer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDataContainer {
	mock := &MockDataContainer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
