// Code generated by mockery v2.34.2. DO NOT EDIT.

package skipper

import mock "github.com/stretchr/testify/mock"

// MockCodec is an autogenerated mock type for the Codec type
type MockCodec struct {
	mock.Mock
}

type MockCodec_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCodec) EXPECT() *MockCodec_Expecter {
	return &MockCodec_Expecter{mock: &_m.Mock}
}

// Unmarshal provides a mock function with given fields: _a0
func (_m *MockCodec) Unmarshal(_a0 []byte) (map[string]interface{}, error) {
	ret := _m.Called(_a0)

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (map[string]interface{}, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]byte) map[string]interface{}); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCodec_Unmarshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unmarshal'
type MockCodec_Unmarshal_Call struct {
	*mock.Call
}

// Unmarshal is a helper method to define mock.On call
//   - _a0 []byte
func (_e *MockCodec_Expecter) Unmarshal(_a0 interface{}) *MockCodec_Unmarshal_Call {
	return &MockCodec_Unmarshal_Call{Call: _e.mock.On("Unmarshal", _a0)}
}

func (_c *MockCodec_Unmarshal_Call) Run(run func(_a0 []byte)) *MockCodec_Unmarshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockCodec_Unmarshal_Call) Return(_a0 map[string]interface{}, _a1 error) *MockCodec_Unmarshal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCodec_Unmarshal_Call) RunAndReturn(run func([]byte) (map[string]interface{}, error)) *MockCodec_Unmarshal_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCodec creates a new instance of MockCodec. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCodec(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCodec {
	mock := &MockCodec{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
