resources:
  location: "westeurope"

  terraform_resource_group:
    name: "rg-${target_name}-${common:project_name}-terraform-${location}"

  resource_group:
    name: "rg-${target_name}-${common:project_name}-${location}"

  terraform_storage_account:
    name: "storage${target_name}terraform"
    state_container:
      name: ${target_name}_tfstate

  vnet:
    name: "vnet-${target_name}-terraform-example"
    address_space:
      - "10.1.0.0/16"
      - "10.2.0.0/16"

    subnets:
      virtual_machines:
        name: "virtual_machines"
        address_prefixes:
          - "10.1.1.0/24"
