// Code generated by mockery v2.42.2. DO NOT EDIT.

package skipper

import (
	skipper "github.com/lukasjarosch/skipper/v1"
	mock "github.com/stretchr/testify/mock"
)

// MockHookablePostSet is an autogenerated mock type for the HookablePostSet type
type MockHookablePostSet struct {
	mock.Mock
}

type MockHookablePostSet_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHookablePostSet) EXPECT() *MockHookablePostSet_Expecter {
	return &MockHookablePostSet_Expecter{mock: &_m.Mock}
}

// RegisterPostSetHook provides a mock function with given fields: _a0
func (_m *MockHookablePostSet) RegisterPostSetHook(_a0 skipper.SetHookFunc) {
	_m.Called(_a0)
}

// MockHookablePostSet_RegisterPostSetHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterPostSetHook'
type MockHookablePostSet_RegisterPostSetHook_Call struct {
	*mock.Call
}

// RegisterPostSetHook is a helper method to define mock.On call
//   - _a0 skipper.SetHookFunc
func (_e *MockHookablePostSet_Expecter) RegisterPostSetHook(_a0 interface{}) *MockHookablePostSet_RegisterPostSetHook_Call {
	return &MockHookablePostSet_RegisterPostSetHook_Call{Call: _e.mock.On("RegisterPostSetHook", _a0)}
}

func (_c *MockHookablePostSet_RegisterPostSetHook_Call) Run(run func(_a0 skipper.SetHookFunc)) *MockHookablePostSet_RegisterPostSetHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(skipper.SetHookFunc))
	})
	return _c
}

func (_c *MockHookablePostSet_RegisterPostSetHook_Call) Return() *MockHookablePostSet_RegisterPostSetHook_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHookablePostSet_RegisterPostSetHook_Call) RunAndReturn(run func(skipper.SetHookFunc)) *MockHookablePostSet_RegisterPostSetHook_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHookablePostSet creates a new instance of MockHookablePostSet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHookablePostSet(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHookablePostSet {
	mock := &MockHookablePostSet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
