// Code generated by mockery v2.42.2. DO NOT EDIT.

package skipper

import (
	data "github.com/lukasjarosch/skipper/data"
	mock "github.com/stretchr/testify/mock"
)

// MockDataGetter is an autogenerated mock type for the DataGetter type
type MockDataGetter struct {
	mock.Mock
}

type MockDataGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDataGetter) EXPECT() *MockDataGetter_Expecter {
	return &MockDataGetter_Expecter{mock: &_m.Mock}
}

// GetPath provides a mock function with given fields: _a0
func (_m *MockDataGetter) GetPath(_a0 data.Path) (data.Value, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetPath")
	}

	var r0 data.Value
	var r1 error
	if rf, ok := ret.Get(0).(func(data.Path) (data.Value, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(data.Path) data.Value); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(data.Value)
	}

	if rf, ok := ret.Get(1).(func(data.Path) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDataGetter_GetPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPath'
type MockDataGetter_GetPath_Call struct {
	*mock.Call
}

// GetPath is a helper method to define mock.On call
//   - _a0 data.Path
func (_e *MockDataGetter_Expecter) GetPath(_a0 interface{}) *MockDataGetter_GetPath_Call {
	return &MockDataGetter_GetPath_Call{Call: _e.mock.On("GetPath", _a0)}
}

func (_c *MockDataGetter_GetPath_Call) Run(run func(_a0 data.Path)) *MockDataGetter_GetPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(data.Path))
	})
	return _c
}

func (_c *MockDataGetter_GetPath_Call) Return(_a0 data.Value, _a1 error) *MockDataGetter_GetPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDataGetter_GetPath_Call) RunAndReturn(run func(data.Path) (data.Value, error)) *MockDataGetter_GetPath_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDataGetter creates a new instance of MockDataGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDataGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDataGetter {
	mock := &MockDataGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
