// Code generated by mockery v2.42.2. DO NOT EDIT.

package skipper

import (
	data "github.com/lukasjarosch/skipper/v1/data"
	mock "github.com/stretchr/testify/mock"
)

// MockPathValueSource is an autogenerated mock type for the PathValueSource type
type MockPathValueSource struct {
	mock.Mock
}

type MockPathValueSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPathValueSource) EXPECT() *MockPathValueSource_Expecter {
	return &MockPathValueSource_Expecter{mock: &_m.Mock}
}

// GetPath provides a mock function with given fields: _a0
func (_m *MockPathValueSource) GetPath(_a0 data.Path) (data.Value, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetPath")
	}

	var r0 data.Value
	var r1 error
	if rf, ok := ret.Get(0).(func(data.Path) (data.Value, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(data.Path) data.Value); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(data.Value)
	}

	if rf, ok := ret.Get(1).(func(data.Path) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPathValueSource_GetPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPath'
type MockPathValueSource_GetPath_Call struct {
	*mock.Call
}

// GetPath is a helper method to define mock.On call
//   - _a0 data.Path
func (_e *MockPathValueSource_Expecter) GetPath(_a0 interface{}) *MockPathValueSource_GetPath_Call {
	return &MockPathValueSource_GetPath_Call{Call: _e.mock.On("GetPath", _a0)}
}

func (_c *MockPathValueSource_GetPath_Call) Run(run func(_a0 data.Path)) *MockPathValueSource_GetPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(data.Path))
	})
	return _c
}

func (_c *MockPathValueSource_GetPath_Call) Return(_a0 data.Value, _a1 error) *MockPathValueSource_GetPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPathValueSource_GetPath_Call) RunAndReturn(run func(data.Path) (data.Value, error)) *MockPathValueSource_GetPath_Call {
	_c.Call.Return(run)
	return _c
}

// SetPath provides a mock function with given fields: _a0, _a1
func (_m *MockPathValueSource) SetPath(_a0 data.Path, _a1 interface{}) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SetPath")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(data.Path, interface{}) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPathValueSource_SetPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPath'
type MockPathValueSource_SetPath_Call struct {
	*mock.Call
}

// SetPath is a helper method to define mock.On call
//   - _a0 data.Path
//   - _a1 interface{}
func (_e *MockPathValueSource_Expecter) SetPath(_a0 interface{}, _a1 interface{}) *MockPathValueSource_SetPath_Call {
	return &MockPathValueSource_SetPath_Call{Call: _e.mock.On("SetPath", _a0, _a1)}
}

func (_c *MockPathValueSource_SetPath_Call) Run(run func(_a0 data.Path, _a1 interface{})) *MockPathValueSource_SetPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(data.Path), args[1].(interface{}))
	})
	return _c
}

func (_c *MockPathValueSource_SetPath_Call) Return(_a0 error) *MockPathValueSource_SetPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPathValueSource_SetPath_Call) RunAndReturn(run func(data.Path, interface{}) error) *MockPathValueSource_SetPath_Call {
	_c.Call.Return(run)
	return _c
}

// Values provides a mock function with given fields:
func (_m *MockPathValueSource) Values() map[string]data.Value {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Values")
	}

	var r0 map[string]data.Value
	if rf, ok := ret.Get(0).(func() map[string]data.Value); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]data.Value)
		}
	}

	return r0
}

// MockPathValueSource_Values_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Values'
type MockPathValueSource_Values_Call struct {
	*mock.Call
}

// Values is a helper method to define mock.On call
func (_e *MockPathValueSource_Expecter) Values() *MockPathValueSource_Values_Call {
	return &MockPathValueSource_Values_Call{Call: _e.mock.On("Values")}
}

func (_c *MockPathValueSource_Values_Call) Run(run func()) *MockPathValueSource_Values_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPathValueSource_Values_Call) Return(_a0 map[string]data.Value) *MockPathValueSource_Values_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPathValueSource_Values_Call) RunAndReturn(run func() map[string]data.Value) *MockPathValueSource_Values_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPathValueSource creates a new instance of MockPathValueSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPathValueSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPathValueSource {
	mock := &MockPathValueSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
