---
name: Example Tests
on: [push, pull_request]
jobs:
  compile_examples:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - run: ./.github/scripts/examples_compile.sh $(pwd)/examples

  run_example_tests:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - run: ./.github/scripts/examples_test.sh $(pwd)/examples
