on: [push, pull_request]
name: skipper-test

env:
  GO_VERSION: "1.21.0"
  GO_VERSION_SHORT: "1.21"
  GOLANGCI_VERSION: "v1.54.0"

permissions:
  contents: read

jobs:
  vet:
    name: "go vet"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v4
      - run: go vet $(go list ./... | grep -v /vendor/)

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: golangci/golangci-lint-action@v4
        with:
          version: ${{ env.GOLANGCI_VERSION }}

  test:
    name: "go test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v4
      - run: go test $(go list ./... | grep -v /vendor/)
