---
target:
  skipper:
    use: 
      - common
      - azure.common
      - azure.resources
      - terraform.identifiers
    components:
      - output_path: /
        input_paths:
          - markdown/README.md
      - output_path: 1_bootstrap
        input_paths:
          - scripts/bootstrap.sh
          - scripts/utils.sh
          - scripts/az.sh
      - output_path: documentation
        input_paths:
          - markdown/docs.md
      - output_path: terraform
        input_paths:
          - terraform/01_resource_group.tf
          - terraform/02_network.tf

  azure:
    common:
      subscription_id: "59efa773-ee54-47d6-a95a-eac3fca3bc24" # random uuid

  # Refactoring terraform identifiers has never been easier. 
  # Just change one variable from the imported class and you're done :)
  terraform:
    identifiers:
      resource_group: "changed_identifier"
