---
target:
  skipper:
    use: 
      - common
      - azure
      - azure.common
      - azure.resources
      - terraform.identifiers
      - components.*
    components:
      - output_path: /
        input_paths:
          - markdown/README.md
      - output_path: component_rename
        input_paths:
          - markdown/AnotherReadme.md
        rename:
          - input_path: markdown/AnotherReadme.md
            filename: README.md


  azure:
    common:
      subscription_id: "59efa773-ee54-47d6-a95a-eac3fca3bc24" # random uuid

  # Refactoring terraform identifiers has never been easier. 
  # Just change one variable from the imported class and you're done :)
  terraform:
    identifiers:
      resource_group: "changed_identifier"
