---
target:
  skipper:
    use: 
      - azure.common
      - azure.resources
      - terraform.identifiers
    components:
      - output_path: /
        input_paths:
          - markdown/README.md
      - output_path: /documentation
        input_paths:
          - markdown/docs.md
      - output_path: terraform
        input_paths:
          - terraform/01_resource_group.tf
          - terraform/02_network.tf

  azure:
    common:
      subscription_id: "45e4fca6-f05b-4354-951a-3ea194d2da85" # random uuid

  # Refactoring terraform identifiers has never been easier. 
  # Just change one variable from the imported class and you're done :)
  terraform:
    identifiers:
      resource_group: "changed_identifier"
